"""set nullable=True to budget_id, category_id and deposit_id in Expense

Revision ID: 206f1cbfdd24
Revises: 7fe1a794a086
Create Date: 2021-03-01 23:57:41.622895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206f1cbfdd24'
down_revision = '7fe1a794a086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
