"""set nullable=True in budget_id and deposit_id in Debt

Revision ID: 35b37a33acdf
Revises: 4a4313703e8f
Create Date: 2021-03-02 00:03:14.690319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b37a33acdf'
down_revision = '4a4313703e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
