"""set nullable=True to budget_id and deposit_id in Saving

Revision ID: 4a4313703e8f
Revises: 0fb79bdf3e3a
Create Date: 2021-03-02 00:01:28.955832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4313703e8f'
down_revision = '0fb79bdf3e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saving', schema=None) as batch_op:
        batch_op.alter_column('deposit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
