"""set nullable to Tru in Incoem.budget_id

Revision ID: 684105e406a0
Revises: eb810a303634
Create Date: 2021-03-01 23:28:30.577048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684105e406a0'
down_revision = 'eb810a303634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('budget_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
