"""delete Income.posting_date

Revision ID: 68509c5cc5f2
Revises: dd4477aeb8ea
Create Date: 2021-03-01 23:07:47.791101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68509c5cc5f2'
down_revision = 'dd4477aeb8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('posting_date')
        batch_op.drop_column('steady_income')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steady_income', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('posting_date', sa.VARCHAR(length=10), nullable=False))

    # ### end Alembic commands ###
