"""add Incoem.stady_income

Revision ID: 7fe1a794a086
Revises: 684105e406a0
Create Date: 2021-03-01 23:31:33.527855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe1a794a086'
down_revision = '684105e406a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('steady_income', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_column('steady_income')

    # ### end Alembic commands ###
